/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JeuMemory;

import javax.swing.ImageIcon;

/**
 *
 * @author bouvr
 */
public class JeuCarte extends javax.swing.JPanel {

    private String urlFace;
    private String urlDos;
    private int id;
    
    public void setUrlFace(String tmp) {
        urlFace = tmp;
    }
    public String getUrlFace() {
        return urlFace;
    }

    public void setUrlDos(String tmp) {
        urlDos = tmp;
    }
    public String getUrlDos() {
        return urlDos;
    }

    public void setId(int tmp) {
        id = tmp;
    }
    public int getId() {
        return id;
    }
    
    private void AffichePhoto(String tmp) {         //Méthode métier
        ImageIcon iconPhoto = new ImageIcon(tmp);   //carte0.png       //  ../Photos/carte0.png
        lblPhoto.setIcon(iconPhoto);
    }
    
    public void TournerVersFace() {
        AffichePhoto(urlFace);
    }

    public void TournerVersDos() {
        AffichePhoto(urlDos);
    }    
    /**
     * Creates new form Carte
     */
    public JeuCarte(String l_urlFace, String l_urlDos, int l_id ) {        //Constructor
        initComponents();
        setUrlFace(l_urlFace);
        setUrlDos(l_urlDos);
        setId(l_id);
        TournerVersDos();        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPhoto = new javax.swing.JLabel();

        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(57, 91));

        lblPhoto.setPreferredSize(new java.awt.Dimension(57, 91));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblPhoto;
    // End of variables declaration//GEN-END:variables
}
